

CompileFlags:
  Add: [
    -Wall,
    -Wextra,
    -pedantic
  ]
  Language: 
    c: [ -std=c23 ]
    cpp: [ -std=c++23 ]

Diagnostics:
  ClangTidy:
    CheckOptions:
      readability-identifier-naming.VariableCase: lower_case
Format:
  Style: file
